version: "3"
services:
  graphdb:
    image: khaller/graphdb-free:10.6.2
    ports:
      - "7200:7200"
      - "7300:7300"
    restart: always
    volumes:
      - "graphdb_data:/opt/graphdb/home"

  #workbench:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  environment:
  #    GRAPHDB_URL: 'http://graphdb:7200'
  #  ports:
  #    - 80
  #  depends_on:
  #    - graphdb
volumes:
    graphdb_data:
