version: "3"
services:
  graphdb:
    image: khaller/graphdb-free:10.8.3
    ports:
      - "7200:7200"
      - "7300:7300"
    restart: always

  dataplat_designer:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: no
    volumes:
      - "./dataplatform_design/src/test/scenarios/:/dataplatform_design/dataplatform_design/src/test/scenarios/"
      - "./dataplatform_design/run_statistics/:/dataplatform_design/dataplatform_design/run_statistics/"
    command:
      - /bin/bash
      - -c
      - |
        sleep 10
        python dataplatform_design/src/test/test_solutions.py
        python dataplatform_design/src/test/plot_statistics.py
    depends_on:
      - graphdb
