version: "3"
services:
  graphdb:
    image: khaller/graphdb-free:10.7.1
    ports:
      - "7200:7200"
      - "7300:7300"
    restart: always
    volumes:
      - "graphdb_data:/opt/graphdb/home"
volumes:
    graphdb_data:
