
graph_db:
  endpoint: http://137.204.74.57:7200
  test: /repositories/DataPlatformDesign
  repository: DataPlatformDesign
  named_graph: http://dpdo_example.com/DPD_Graph

ontologies:
  namespaces:
      DPDO: http://www.semanticweb.org/manuele.pasini2/ontologies/2024/4/DPDO#
      TagTaxonomy: http://www.semanticweb.org/manuele.pasini2/ontologies/2024/4/TagTaxonomy#
      ServiceEcosystem: http://www.semanticweb.org/manuele.pasini2/ontologies/2024/4/ServiceEcosystem#
      DFD: http://www.semanticweb.org/manuele.pasini2/ontologies/2024/4/DFD#
  paths:
      DPDO: dataplatform_design/src/resources/DPDO.ttl
      TagTaxonomy: dataplatform_design/src/resources/TagTaxonomy.ttl
      ServiceEcosystem: dataplatform_design/src/resources/ServiceEcosystem.ttl
      DFD: dataplatform_design/src/resources/DFD.ttl
  prefix:
      DPDO: DPDO
      TagTaxonomy: TagTaxonomy
      ServiceEcosystem: ServiceEcosystem
      DFD: DFD